# -*- coding: utf-8 -*-
"""Predict 2020-2021 Post Season

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1e18dzJIBZyQkdLjFXiOUpRLi0IGF7uKQ
"""

# Mount google Drive
from google.colab import drive
import pandas as pd

drive.mount('/content/drive')

"""# Read Data

"""

X1617 = pd.read_excel('/content/drive/MyDrive/NBA/1617.xlsx')
X1718 = pd.read_excel('/content/drive/MyDrive/NBA/1718.xlsx')
X1819 = pd.read_excel('/content/drive/MyDrive/NBA/1819.xlsx')
X1920 = pd.read_excel('/content/drive/MyDrive/NBA/1920.xlsx')

train = pd.concat([X1617,X1718,X1819,X1920])

train = train[train.Team != "League Average"]

#train = train.drop(['Team'], axis = 1)

ylabel = train['Playoffs']

train = train.drop(['Playoffs'], axis = 1)

from sklearn.preprocessing import OrdinalEncoder

encoder = OrdinalEncoder()
train = encoder.fit_transform(train)

type(train)

from sklearn.linear_model import LinearRegression

model = LinearRegression()
model.fit(train, ylabel)

#X_predict = []  # put the dates of which you want to predict kwh here
#y_predict = model.predict(X_predict)

X2021 = pd.read_excel('/content/drive/MyDrive/NBA/X2021.xlsx')

Val = encoder.fit_transform(X2021)

X2021['Predictions'] = model.predict(Val).tolist()

X2021.sort_values(['Predictions'],ascending= False).head(16)

print(model)

import statsmodels.api as sm      
train = sm.add_constant(train)
lm_1 = sm.OLS(ylabel, train).fit()
lm_1.summary()